name: Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7]
        experimental: [false]

        include:
          - python-version: 3.6
            experimental: true

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: run tests
        if: ${{ matrix.python-version == '2.7' }}
        run: python -c "import tester; tester.ok()"

      - name: run tests KO
        if: ${{ matrix.python-version != '2.7' }}
        run: python -c "import tester; tester.ko()"
